title: HMMM - Senior Project # your name or (website title) here
logo: "/images/otherlogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Calvin University
  <br><br>
  2019-2020 
  <br><br>
  
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
